name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare env
      run: ./tests/prepare-server.sh
    - name: Run tests
      run: cargo test
    - name: Clear env
      run: ./tests/shutdown-server.sh
